config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#home'
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index] do
    resources :messages do
    end
  end
  get '/profile', to: 'users#profile'
  get '/results', to: 'search#results'
end

app/models/user.rb
class User < ActiveRecord::Base

	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_attached_file :avatar, :styles => { :medium => "250x250>", :thumb => "150x150#" }, :default_url => ActionController::Base.helpers.asset_path('medium.png')
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/,
    
    :url  => ":s3_domain_url",
    :path => "public/avatars/:id/:style_:basename.:extension",
	:storage => :fog,
    :fog_credentials => {
        provider: 'AWS',
        aws_access_key_id: ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
    },
    fog_directory: ENV["FOG_DIRECTORY"]

	validates :name, presence: true
	validates :date_of_birth, presence: true
	validates :gender, presence: true
	
	enum gender: {:"Guy" => 0, :"Girl" => 1}
	
	enum orientation: {:"Straight" => 0, :"Gay" => 1, :"Bi" => 3}
	
	enum relationship: {:"Single" => 0, :"Taken" => 1, :"Married" => 3}
	
	enum education: {:"High School" => 0, :"Course Certification" => 1, :"College" => 2, :"Grad School" => 3, :"PhD" => 4}

	has_and_belongs_to_many :interests
	accepts_nested_attributes_for :interests, :allow_destroy => true, :reject_if => :all_blank
 
	has_and_belongs_to_many :languages
 	accepts_nested_attributes_for :languages, :allow_destroy => true, :reject_if => :all_blank

	def age
		age = Date.today.year - date_of_birth.year
		if Date.today.month < date_of_birth.month
		    if Date.today.day < date_of_birth.day
				age = age - 1
			end
		end
		age
	end

	def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end

	has_many :messages, class_name: "Message", foreign_key: "recipient_id"
	has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    interests_ids = params[:user][:interests_ids] || []
    current_user.interests = interests_ids.map {|id| Interest.find(id)}
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 
	before_action :authenticate_user!

  def profile
    @user = current_user
    render 'users/profile'
  end

  def edit
  	@user = current_user
  	render 'users/edit'
  end

  def home
    @user = current_user
    render :home
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).shuffle
    else
      @users = User.all.shuffle
    end
  end

   def sender
      @user = User.find(params[:id])
    end

    def recipient
      @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>GoJunket</title>
	</head>
		<center>
		<body>
			<br><br><br>
			<div class="home"><br>
			<h1>Wanna GoJunket?</h1>
			<h3>Who, what, where, and when?</h3>
			<div><em>(To select multiple options, hold down the shift key.<br>All fields must have at least one selection.)</em>
			</div>
			<br>
				<%= form_tag(results_path, :method => "get", id: "param_search") do %>
				I wanna chill with a<br>
				<%= select_tag(:gender, options_for_select(User.genders.to_a), :style => "width:55px", :style=>"height:38px", multiple: true) %>
			<br>
			<br>Aged<br><%= select @age, :min_age, (18..100).to_a, include_blank: true  %>
				to<%= select @age, :max_age, (18..100).to_a, include_blank: true %>
			
			<div><br>Located in the city of</div>
				<%= text_field_tag :location %>
			
			<div><br>In the state of <em>(Ex: NE)</em></div>
				<%= text_field_tag :state, params[:search], :maxlength => 2 %>
			
			<div><br>Who is</div>
				<%= select_tag(:relationship, options_for_select(User.relationships.to_a), :style => "width:75px", :style=>"height:55px",  multiple: true) %>
			
			<div><br>Whose sexual orientation is</div>
				<%= select_tag(:orientation, options_for_select(User.orientations.to_a), :style => "width:75px", :style=>"height:55px",  multiple: true) %>
			
			<div><br>Whose highest education level is</div>
				<%= select_tag(:education, options_for_select(User.educations.to_a), :style => "width:150px", multiple: true) %>
			
			<div><br>Who has kiddos?</div>
				<%= select_tag(:kids, options_for_select([['Yup', true], ['Nope', false]]), :style => "width:75px", :style=>"height:38px",  multiple: true) %>
			
			<div><br>Who drinks?</div>
				<%= select_tag(:drinks, options_for_select([['Yup', true], ['Nope', false]]), :style => "width:75px", :style=>"height:38px",  multiple: true) %>
			
			<div><br>Who smokes?</div>
				<%= select_tag(:smokes, options_for_select([['Yup', true], ['Nope', false]]), :style => "width:75px", :style=>"height:38px",  multiple: true) %>
			
			<div><br>What would you like this person to be interested in?</div>
				<%= select_tag(:interests, options_for_select(["Animals", "Art", "Astrology", "Astronomy", "Baseball", "Basketball", "Board Games", "Board Sports", "Boxing", "Casual Sex", "Cats", "Computer Programming", "Cooking", "Cosplay", "Cycling", "Dance", "Drama", "Drawing and Painting", "Drinking", "Dogs", "Eating", "Fashion", "Fishing", "Food", "Football", "Gambling", "Gaming", "Hooping", "Hunting", "Internet", "Jogging", "Legos", "Magic", "Martial Arts", "Movies", "Music", "Napping", "Paintball", "Photography", "Pilates", "Puzzles", "Reading", "Religion", "Rock Climbing", "Sailing", "Sarcasm", "Shooting", "Skateboarding", "Skiing", "Snowboarding", "Soccer", "Sports (General)", "Surfing", "Swimming", "Technology", "Traveling", "Video Games", "Writing", "Work", "Yoga"], "Animals"), :style => "width:175px", multiple: true) %>
			<br><br></div><br>
			<button class="submit" type="submit" form="param_search" value="Submit">Find a GoJunkie</button>
				<% end %>
		</body>
		</center>
</html>

app/views/users/index.html.erb
<br><br><br><center>
<body><div class="users"><br>
<h2>Meet your fellow GoJunkies</h2>
<% @users.each do |user| %><br>
	<li><%= link_to user.name, user_path(user) %><br></li>
	<%= link_to user_path(user) do %>
	<%= image_tag user.avatar.url(:thumb), :style => "border: 1px solid Cyan" %><br>
<% end %><% end %>
</body><br><br></div>
</center>

app/views/users/profile.html.erb
<br><br><br><center>
<body><div class="profile"><br>
<h2>Howdy, <%= current_user.name %>!</h2>

<p><%= image_tag current_user.avatar.url(:thumb), :style => "border: 1px solid Cyan"%></p>

<p>Email:  <%= current_user.email %></p>

<p>Current Location:  <%= current_user.location %>, <%= current_user.state %></p>

<p>Sex:  <%= current_user.gender %></p>

<p>Age: <%= current_user.age %> years old</p>

<p>Relationship Status: <%= current_user.relationship %></p>

<p>Orientation:  <%= current_user.orientation %></p>

<p>Education:  <%= current_user.education %></p>

<p>Kids?  <%= current_user.kids ? "Yup" : "Nope" %></p>

<p>Drinks?  <%= current_user.drinks ? "Yup" : "Nope" %></p>

<p>Smokes?  <%= current_user.smokes ? "Yup" : "Nope" %></p>

<p>Interests:<% current_user.interests.each do |int| %><br>
	<%= int.name %>
	<% end %>
</p>

<p>The 411 on me:<br><%= current_user.description %></p><br>
</div>
	<%= link_to("Edit my profile", edit_user_registration_path)%>
<br></body>
</center>

app/views/users/show.html.erb
<br><br><br><center>
<body><div class="show"><br>
	<h2>Wanna GoJunket with <%= @user.name %>?</h2>

	<p><%= image_tag @user.avatar.url(:medium) %></p>

	<p> <%= @user.email %></p>

	<p>Current Location:  <%= @user.location %>, <%= @user.state %></p>

	<p>Sex:  <%= @user.gender %></p>

	<p>Age: <%= @user.age %> years old</p>

	<p>Relationship Status: <%= @user.relationship %></p>

	<p>Orientation:  <%= @user.orientation %></p>

	<p>Education:  <%= @user.education %></p>

	<p>Kids?  <%= @user.kids ? "Yup" : "Nope" %></p>

	<p>Drinks?  <%= @user.drinks ? "Yup" : "Nope" %></p>

	<p>Smokes?  <%= @user.smokes ? "Yup" : "Nope" %></p>

	<p>Interests:<% @user.interests.each do |int| %><br>
		<%= int.name %>
		<% end %>
	</p>

	<p>The 411 on me:<br><%= @user.description %></p>

	
	<p><%= link_to "Send Message", new_user_message_path(@user.id), :class => "buttons" %> </p><br></div>

		<%= link_to 'Back', :back %>
</body>
</center>