config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#home'
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index] do
    resources :messages do
    end
  end
  get '/profile', to: 'users#profile'
  get '/results', to: 'search#results'
end

app/views/layouts/_menu.html.erb
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Posts', '#' %></li>
            <% if current_user %>
            <li><%= link_to 'Edit Profile.',edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

            <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <title>GoJunket</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
  <div class="logo", align="center"><%= image_tag("gojunketsquare.png", :alt => "rss feed", :size => "420x120" )%></div>

    <div class="page-header", align="right">
      <% if user_signed_in? %>
        <%= link_to 'Home', root_path, :class => "buttons" %>
        <%= link_to 'My profile', profile_path, :class => "buttons" %>
        <%= link_to 'Inbox', user_messages_path(current_user.id), :class => "buttons" %>
        <%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE', :class => "buttons" %>
        <% else %>
        <%= link_to 'Join', new_user_registration_path, :class => "buttons" %>
        <%= link_to 'Log In', new_user_session_path, :class => "buttons" %>
        <% end %>
    </div>

    <div class="search_bar", align="left">
        <%= form_tag(users_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Name",  :class => "search-form" %>
        <%= submit_tag "Find GoJunkie", :name => nil, :class => "buttons"  %>
        <% end %>
    </div>
      <div class="notice">
      <p class="notice" align="center"><%= notice %></p>
      <p class="alert" align="center"><%= alert %></p>

  <div id="top_bar" align="center"><div class="container-fluid"></div>
  </div>
  </div><%= yield %>
  </body>
  <footer><div style="clear: both"><h4 style="float: left">Copyright GoJunket 2015<br>GoJunket@gmail.com</h4><h4 style="float: right"></h4></div></footer>
</html>